### ISSUE TITLE
Add irsim

### ISSUE THREAD

**Issue by mithro** [hdl/containers#30]

**Comment by umarcor** [comment]
Images `irsim` and `magic/irsim` were added in https://github.com/hdl/containers/commit/dacd0cffc062251ab1b927f4f20f19ca842c6ba4 and https://github.com/hdl/containers/commit/f9830bf5e1e600bb645ff21d03bf12da22e46f4d. I took the following screenshot using image `gcr.io/hdl-containers/magic/irsim` on Windows 10, using Docker with HyperV backend, executed on MSYS2 using x11docker and runx with VcxSrv:

![image](https://user-images.githubusercontent.com/38422348/169671620-701d3af1-402f-4709-87db-5b4a82a9e94f.png)

```
# x11docker --runx --no-auth gcr.io/hdl-containers/magic/irsim irsim
x11docker note: Enabled X over TCP instead of sharing unix socket.

x11docker WARNING: Option --no-auth: SECURITY RISK!
  Allowing access to new X server for everyone.
  Your X server is accessable over TCP network without any restriction.
  That can be abused to take control over your system.
```
