### ISSUE TITLE
Update cocotb to 1.5?

### ISSUE THREAD

**Issue by rodrigomelo9** [hdl/containers#43]
Is stuck at 1.4:
```
osvb.dockerfile:38: && git clone -b stable/1.4 --recurse-submodules https://github.com/cocotb/cocotb /tmp/cocotb \
```
Or maybe to provide a fine-grain, updated, cocotb image?

**Comment by umarcor** [comment]
That was an oversight (probably a copy and paste mistake). We try to build master/development/head versions of all the tools, except a few. Cocotb should not be in the exception list.

Thanks for letting us know!
